ALTER TABLE wallets
ADD COLUMN currency VARCHAR(10) NOT NULL DEFAULT 'IDR',
ADD COLUMN balance  NUMERIC(15,2) NOT NULL DEFAULT 0,
ADD COLUMN goals    VARCHAR(255);

-- Down
-- ALTER TABLE wallets DROP COLUMN goals, DROP COLUMN balance, DROP COLUMN currency;
