ALTER TABLE wallets ADD COLUMN IF NOT EXISTS currency VARCHAR(10) NOT NULL DEFAULT 'IDR';
ALTER TABLE wallets ADD COLUMN IF NOT EXISTS balance NUMERIC(15,2) NOT NULL DEFAULT 0;
ALTER TABLE wallets ADD COLUMN IF NOT EXISTS goals VARCHAR(255);

-- Down
-- ALTER TABLE wallets DROP COLUMN IF EXISTS goals, DROP COLUMN IF EXISTS balance, DROP COLUMN IF EXISTS currency;
