package handlers

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/redis/go-redis/v9"
	"github.com/yanaatere/expense_tracking/auth"
)

type BotHandler struct {
	redis *redis.Client
}

func NewBotHandler(redisClient *redis.Client) *BotHandler {
	return &BotHandler{redis: redisClient}
}

type BotLinkRequest struct {
	LinkCode string `json:"link_code"`
}

// @Summary Link Telegram bot to Monex account
// @Description Consumes a 6-digit link code generated by the Telegram bot and stores the user's JWT in the bot session
// @Tags Bot
// @Accept json
// @Produce json
// @Param request body BotLinkRequest true "Link request"
// @Success 200 {object} object
// @Failure 400 {object} MessageResponse
// @Failure 401 {object} MessageResponse
// @Failure 500 {object} MessageResponse
// @Router /api/bot/link [post]
func (h *BotHandler) LinkBotUser(w http.ResponseWriter, r *http.Request) {
	var input BotLinkRequest
	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		WriteError(w, http.StatusBadRequest, err.Error())
		return
	}
	if input.LinkCode == "" {
		WriteError(w, http.StatusBadRequest, "link_code is required")
		return
	}

	userID := auth.GetUserIDFromContext(r.Context())
	if userID == 0 {
		WriteError(w, http.StatusUnauthorized, "Unauthorized")
		return
	}

	// Extract raw JWT from Authorization header — stored in bot session for backend calls
	authHeader := r.Header.Get("Authorization")
	jwtToken := strings.TrimPrefix(authHeader, "Bearer ")

	// Consume the link code atomically (prevents reuse)
	chatIDStr, err := h.redis.GetDel(r.Context(), fmt.Sprintf("link_code:%s", input.LinkCode)).Result()
	if err == redis.Nil {
		WriteError(w, http.StatusBadRequest, "Invalid or expired link code")
		return
	}
	if err != nil {
		WriteError(w, http.StatusInternalServerError, "Failed to validate link code")
		return
	}

	// Retrieve the existing bot session
	sessionKey := fmt.Sprintf("session:%s", chatIDStr)
	sessionJSON, err := h.redis.Get(r.Context(), sessionKey).Result()
	if err == redis.Nil {
		WriteError(w, http.StatusBadRequest, "Bot session not found. User must start the bot first by sending /start.")
		return
	}
	if err != nil {
		WriteError(w, http.StatusInternalServerError, "Failed to retrieve bot session")
		return
	}

	// Parse session as a generic map to update only the linking fields
	var session map[string]interface{}
	if err := json.Unmarshal([]byte(sessionJSON), &session); err != nil {
		WriteError(w, http.StatusInternalServerError, "Failed to parse bot session")
		return
	}

	session["monex_user_id"] = userID
	session["jwt_token"] = jwtToken
	session["updated_at"] = time.Now().UTC().Format(time.RFC3339Nano)

	updated, err := json.Marshal(session)
	if err != nil {
		WriteError(w, http.StatusInternalServerError, "Failed to serialize session")
		return
	}

	// Preserve existing TTL; fall back to 30 minutes if session has no TTL set
	ttl := h.redis.TTL(r.Context(), sessionKey).Val()
	if ttl <= 0 {
		ttl = 30 * time.Minute
	}
	if err := h.redis.SetEx(r.Context(), sessionKey, string(updated), ttl).Err(); err != nil {
		WriteError(w, http.StatusInternalServerError, "Failed to save bot session")
		return
	}

	WriteSuccess(w, http.StatusOK, map[string]string{"message": "Bot linked successfully"})
}
