// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAvgMonthlyCategorySpend = `-- name: GetAvgMonthlyCategorySpend :many
SELECT
    COALESCE(category_id::text, 'Uncategorized') AS category_name,
    AVG(monthly_total) AS avg_monthly
FROM (
    SELECT t.category_id,
           DATE_TRUNC('month', t.transaction_date) AS month,
           SUM(t.amount) AS monthly_total
    FROM transactions t
    WHERE t.user_id = $1
      AND t.type = 'expense'
      AND t.transaction_date >= CURRENT_DATE - INTERVAL '3 months'
    GROUP BY t.category_id, DATE_TRUNC('month', t.transaction_date)
) sub
GROUP BY category_id
`

type GetAvgMonthlyCategorySpendRow struct {
	CategoryName interface{} `json:"category_name"`
	AvgMonthly   float64     `json:"avg_monthly"`
}

func (q *Queries) GetAvgMonthlyCategorySpend(ctx context.Context, userID int32) ([]GetAvgMonthlyCategorySpendRow, error) {
	rows, err := q.db.Query(ctx, getAvgMonthlyCategorySpend, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAvgMonthlyCategorySpendRow
	for rows.Next() {
		var i GetAvgMonthlyCategorySpendRow
		if err := rows.Scan(&i.CategoryName, &i.AvgMonthly); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyCategoryTotals = `-- name: GetMonthlyCategoryTotals :many
SELECT
    COALESCE(t.category_id::text, 'Uncategorized') AS category_name,
    t.type,
    SUM(t.amount) AS total,
    COUNT(*) AS count
FROM transactions t
WHERE t.user_id = $1
  AND DATE_TRUNC('month', t.transaction_date) = DATE_TRUNC('month', CURRENT_DATE)
GROUP BY t.category_id, t.type
`

type GetMonthlyCategoryTotalsRow struct {
	CategoryName interface{} `json:"category_name"`
	Type         string      `json:"type"`
	Total        int64       `json:"total"`
	Count        int64       `json:"count"`
}

func (q *Queries) GetMonthlyCategoryTotals(ctx context.Context, userID int32) ([]GetMonthlyCategoryTotalsRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyCategoryTotals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyCategoryTotalsRow
	for rows.Next() {
		var i GetMonthlyCategoryTotalsRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.Type,
			&i.Total,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsForAI = `-- name: GetTransactionsForAI :many
SELECT t.type, t.amount, t.description, t.transaction_date,
       t.category_id, t.sub_category_id
FROM transactions t
WHERE t.user_id = $1
  AND t.transaction_date >= $2
ORDER BY t.transaction_date DESC
LIMIT 200
`

type GetTransactionsForAIParams struct {
	UserID          int32       `json:"user_id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
}

type GetTransactionsForAIRow struct {
	Type            string         `json:"type"`
	Amount          pgtype.Numeric `json:"amount"`
	Description     pgtype.Text    `json:"description"`
	TransactionDate pgtype.Date    `json:"transaction_date"`
	CategoryID      pgtype.Int4    `json:"category_id"`
	SubCategoryID   pgtype.Int4    `json:"sub_category_id"`
}

func (q *Queries) GetTransactionsForAI(ctx context.Context, arg GetTransactionsForAIParams) ([]GetTransactionsForAIRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsForAI, arg.UserID, arg.TransactionDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsForAIRow
	for rows.Next() {
		var i GetTransactionsForAIRow
		if err := rows.Scan(
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.TransactionDate,
			&i.CategoryID,
			&i.SubCategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
