// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustBalance = `-- name: AdjustBalance :one
INSERT INTO balances (user_id, total_balance)
VALUES ($1, $2)
ON CONFLICT (user_id)
DO UPDATE SET total_balance = balances.total_balance + $2, updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, total_balance, created_at, updated_at
`

type AdjustBalanceParams struct {
	UserID       int32          `json:"user_id"`
	TotalBalance pgtype.Numeric `json:"total_balance"`
}

func (q *Queries) AdjustBalance(ctx context.Context, arg AdjustBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, adjustBalance, arg.UserID, arg.TotalBalance)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT id, user_id, total_balance, created_at, updated_at
FROM balances
WHERE user_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, userID int32) (Balance, error) {
	row := q.db.QueryRow(ctx, getBalance, userID)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBalanceByCategory = `-- name: GetBalanceByCategory :many
SELECT 
    c.id AS category_id,
    c.name AS category_name,
    t.type,
    COALESCE(SUM(t.amount), 0)::numeric AS total_amount,
    COUNT(t.id)::bigint AS transaction_count
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
WHERE t.user_id = $1
GROUP BY c.id, c.name, t.type
ORDER BY total_amount DESC
`

type GetBalanceByCategoryRow struct {
	CategoryID       pgtype.Int4    `json:"category_id"`
	CategoryName     pgtype.Text    `json:"category_name"`
	Type             string         `json:"type"`
	TotalAmount      pgtype.Numeric `json:"total_amount"`
	TransactionCount int64          `json:"transaction_count"`
}

func (q *Queries) GetBalanceByCategory(ctx context.Context, userID int32) ([]GetBalanceByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getBalanceByCategory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBalanceByCategoryRow
	for rows.Next() {
		var i GetBalanceByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.Type,
			&i.TotalAmount,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBalanceByDateRange = `-- name: GetBalanceByDateRange :one
SELECT 
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END), 0)::numeric AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0)::numeric AS total_expense,
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE -amount END), 0)::numeric AS balance
FROM transactions
WHERE user_id = $1 
  AND transaction_date >= $2 
  AND transaction_date <= $3
`

type GetBalanceByDateRangeParams struct {
	UserID            int32       `json:"user_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type GetBalanceByDateRangeRow struct {
	TotalIncome  pgtype.Numeric `json:"total_income"`
	TotalExpense pgtype.Numeric `json:"total_expense"`
	Balance      pgtype.Numeric `json:"balance"`
}

func (q *Queries) GetBalanceByDateRange(ctx context.Context, arg GetBalanceByDateRangeParams) (GetBalanceByDateRangeRow, error) {
	row := q.db.QueryRow(ctx, getBalanceByDateRange, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	var i GetBalanceByDateRangeRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense, &i.Balance)
	return i, err
}

const getMonthlyBalance = `-- name: GetMonthlyBalance :many
SELECT 
    DATE_TRUNC('month', transaction_date::timestamp)::date AS month,
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END), 0)::numeric AS income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0)::numeric AS expense,
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE -amount END), 0)::numeric AS net
FROM transactions
WHERE user_id = $1
GROUP BY DATE_TRUNC('month', transaction_date::timestamp)
ORDER BY month DESC
`

type GetMonthlyBalanceRow struct {
	Month   pgtype.Date    `json:"month"`
	Income  pgtype.Numeric `json:"income"`
	Expense pgtype.Numeric `json:"expense"`
	Net     pgtype.Numeric `json:"net"`
}

func (q *Queries) GetMonthlyBalance(ctx context.Context, userID int32) ([]GetMonthlyBalanceRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyBalance, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyBalanceRow
	for rows.Next() {
		var i GetMonthlyBalanceRow
		if err := rows.Scan(
			&i.Month,
			&i.Income,
			&i.Expense,
			&i.Net,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBalance = `-- name: GetUserBalance :one
SELECT 
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END), 0)::numeric AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0)::numeric AS total_expense
FROM transactions
WHERE user_id = $1
`

type GetUserBalanceRow struct {
	TotalIncome  pgtype.Numeric `json:"total_income"`
	TotalExpense pgtype.Numeric `json:"total_expense"`
}

func (q *Queries) GetUserBalance(ctx context.Context, userID int32) (GetUserBalanceRow, error) {
	row := q.db.QueryRow(ctx, getUserBalance, userID)
	var i GetUserBalanceRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const recalculateBalance = `-- name: RecalculateBalance :one
INSERT INTO balances (user_id, total_balance)
VALUES ($1, (
    SELECT COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE -amount END), 0)
    FROM transactions WHERE user_id = $1
))
ON CONFLICT (user_id)
DO UPDATE SET 
    total_balance = (
        SELECT COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE -amount END), 0)
        FROM transactions WHERE user_id = $1
    ),
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, total_balance, created_at, updated_at
`

func (q *Queries) RecalculateBalance(ctx context.Context, userID int32) (Balance, error) {
	row := q.db.QueryRow(ctx, recalculateBalance, userID)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBalance = `-- name: UpsertBalance :one
INSERT INTO balances (user_id, total_balance)
VALUES ($1, $2)
ON CONFLICT (user_id)
DO UPDATE SET total_balance = $2, updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, total_balance, created_at, updated_at
`

type UpsertBalanceParams struct {
	UserID       int32          `json:"user_id"`
	TotalBalance pgtype.Numeric `json:"total_balance"`
}

func (q *Queries) UpsertBalance(ctx context.Context, arg UpsertBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, upsertBalance, arg.UserID, arg.TotalBalance)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
