// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budget.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (user_id, category_id, category_name, budget_limit, period, title, notification_enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, category_name)
DO UPDATE SET
    budget_limit         = EXCLUDED.budget_limit,
    period               = EXCLUDED.period,
    title                = EXCLUDED.title,
    notification_enabled = EXCLUDED.notification_enabled,
    updated_at           = NOW()
RETURNING id, user_id, category_id, category_name, budget_limit, period, title, notification_enabled, created_at, updated_at
`

type CreateBudgetParams struct {
	UserID              int32          `json:"user_id"`
	CategoryID          pgtype.Int4    `json:"category_id"`
	CategoryName        string         `json:"category_name"`
	BudgetLimit         pgtype.Numeric `json:"budget_limit"`
	Period              string         `json:"period"`
	Title               pgtype.Text    `json:"title"`
	NotificationEnabled bool           `json:"notification_enabled"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.UserID,
		arg.CategoryID,
		arg.CategoryName,
		arg.BudgetLimit,
		arg.Period,
		arg.Title,
		arg.NotificationEnabled,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.CategoryName,
		&i.BudgetLimit,
		&i.Period,
		&i.Title,
		&i.NotificationEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets WHERE id = $1 AND user_id = $2
`

type DeleteBudgetParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) error {
	_, err := q.db.Exec(ctx, deleteBudget, arg.ID, arg.UserID)
	return err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, user_id, category_id, category_name, budget_limit, period, title, notification_enabled, created_at, updated_at
FROM budgets
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetBudgetByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetBudgetByID(ctx context.Context, arg GetBudgetByIDParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByID, arg.ID, arg.UserID)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.CategoryName,
		&i.BudgetLimit,
		&i.Period,
		&i.Title,
		&i.NotificationEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetsByUser = `-- name: GetBudgetsByUser :many
SELECT id, user_id, category_id, category_name, budget_limit, period, title, notification_enabled, created_at, updated_at
FROM budgets
WHERE user_id = $1
ORDER BY period, category_name
`

func (q *Queries) GetBudgetsByUser(ctx context.Context, userID int32) ([]Budget, error) {
	rows, err := q.db.Query(ctx, getBudgetsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.CategoryName,
			&i.BudgetLimit,
			&i.Period,
			&i.Title,
			&i.NotificationEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets
SET category_id          = $3,
    category_name        = $4,
    budget_limit         = $5,
    period               = $6,
    title                = $7,
    notification_enabled = $8,
    updated_at           = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, category_name, budget_limit, period, title, notification_enabled, created_at, updated_at
`

type UpdateBudgetParams struct {
	ID                  int32          `json:"id"`
	UserID              int32          `json:"user_id"`
	CategoryID          pgtype.Int4    `json:"category_id"`
	CategoryName        string         `json:"category_name"`
	BudgetLimit         pgtype.Numeric `json:"budget_limit"`
	Period              string         `json:"period"`
	Title               pgtype.Text    `json:"title"`
	NotificationEnabled bool           `json:"notification_enabled"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudget,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.CategoryName,
		arg.BudgetLimit,
		arg.Period,
		arg.Title,
		arg.NotificationEnabled,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.CategoryName,
		&i.BudgetLimit,
		&i.Period,
		&i.Title,
		&i.NotificationEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
