// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	ID           int32            `json:"id"`
	UserID       int32            `json:"user_id"`
	TotalBalance pgtype.Numeric   `json:"total_balance"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Category struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Transaction struct {
	ID              int32            `json:"id"`
	UserID          int32            `json:"user_id"`
	Type            string           `json:"type"`
	Amount          pgtype.Numeric   `json:"amount"`
	Description     pgtype.Text      `json:"description"`
	CategoryID      pgtype.Int4      `json:"category_id"`
	TransactionDate pgtype.Date      `json:"transaction_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        int32            `json:"id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
