// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	ID           int32            `json:"id"`
	UserID       int32            `json:"user_id"`
	TotalBalance pgtype.Numeric   `json:"total_balance"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Category struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	ParentID    pgtype.Int4      `json:"parent_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Transaction struct {
	ID              int32            `json:"id"`
	UserID          int32            `json:"user_id"`
	Type            string           `json:"type"`
	Amount          pgtype.Numeric   `json:"amount"`
	Description     pgtype.Text      `json:"description"`
	CategoryID      pgtype.Int4      `json:"category_id"`
	SubCategoryID   pgtype.Int4      `json:"sub_category_id"`
	WalletID        pgtype.Int4      `json:"wallet_id"`
	ReceiptImageUrl pgtype.Text      `json:"receipt_image_url"`
	TransactionDate pgtype.Date      `json:"transaction_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type Wallet struct {
	ID        int32            `json:"id"`
	UserID    int32            `json:"user_id"`
	Name      string           `json:"name"`
	Type      string           `json:"type"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Currency  string           `json:"currency"`
	Balance   pgtype.Numeric   `json:"balance"`
	Goals     pgtype.Text      `json:"goals"`
}

type User struct {
	ID                   int32            `json:"id"`
	Username             string           `json:"username"`
	Email                string           `json:"email"`
	Password             string           `json:"password"`
	PasswordResetToken   pgtype.Text      `json:"password_reset_token"`
	PasswordResetExpires pgtype.Timestamp `json:"password_reset_expires"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}
