// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recurring_transaction.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurringTransaction = `-- name: CreateRecurringTransaction :one
INSERT INTO recurring_transactions (user_id, title, type, amount, category_id, sub_category_id, wallet_id, frequency, start_date, end_date, next_execution_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, title, type, amount, category_id, sub_category_id, wallet_id, frequency, start_date, end_date, is_active, next_execution_date, created_at, updated_at
`

type CreateRecurringTransactionParams struct {
	UserID            int32          `json:"user_id"`
	Title             string         `json:"title"`
	Type              string         `json:"type"`
	Amount            pgtype.Numeric `json:"amount"`
	CategoryID        pgtype.Int4    `json:"category_id"`
	SubCategoryID     pgtype.Int4    `json:"sub_category_id"`
	WalletID          pgtype.Int4    `json:"wallet_id"`
	Frequency         string         `json:"frequency"`
	StartDate         pgtype.Date    `json:"start_date"`
	EndDate           pgtype.Date    `json:"end_date"`
	NextExecutionDate pgtype.Date    `json:"next_execution_date"`
}

func (q *Queries) CreateRecurringTransaction(ctx context.Context, arg CreateRecurringTransactionParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, createRecurringTransaction,
		arg.UserID,
		arg.Title,
		arg.Type,
		arg.Amount,
		arg.CategoryID,
		arg.SubCategoryID,
		arg.WalletID,
		arg.Frequency,
		arg.StartDate,
		arg.EndDate,
		arg.NextExecutionDate,
	)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.Amount,
		&i.CategoryID,
		&i.SubCategoryID,
		&i.WalletID,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.NextExecutionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateRecurringTransaction = `-- name: DeactivateRecurringTransaction :exec
UPDATE recurring_transactions
SET is_active = FALSE, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeactivateRecurringTransaction(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deactivateRecurringTransaction, id)
	return err
}

const deleteRecurringTransaction = `-- name: DeleteRecurringTransaction :exec
DELETE FROM recurring_transactions
WHERE id = $1 AND user_id = $2
`

type DeleteRecurringTransactionParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteRecurringTransaction(ctx context.Context, arg DeleteRecurringTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteRecurringTransaction, arg.ID, arg.UserID)
	return err
}

const getRecurringTransaction = `-- name: GetRecurringTransaction :one
SELECT id, user_id, title, type, amount, category_id, sub_category_id, wallet_id, frequency, start_date, end_date, is_active, next_execution_date, created_at, updated_at
FROM recurring_transactions
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetRecurringTransactionParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetRecurringTransaction(ctx context.Context, arg GetRecurringTransactionParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, getRecurringTransaction, arg.ID, arg.UserID)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.Amount,
		&i.CategoryID,
		&i.SubCategoryID,
		&i.WalletID,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.NextExecutionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueRecurringTransactions = `-- name: ListDueRecurringTransactions :many
SELECT id, user_id, title, type, amount, category_id, sub_category_id, wallet_id, frequency, start_date, end_date, is_active, next_execution_date, created_at, updated_at
FROM recurring_transactions
WHERE is_active = TRUE AND next_execution_date <= $1
ORDER BY next_execution_date ASC
`

func (q *Queries) ListDueRecurringTransactions(ctx context.Context, nextExecutionDate pgtype.Date) ([]RecurringTransaction, error) {
	rows, err := q.db.Query(ctx, listDueRecurringTransactions, nextExecutionDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringTransaction
	for rows.Next() {
		var i RecurringTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Type,
			&i.Amount,
			&i.CategoryID,
			&i.SubCategoryID,
			&i.WalletID,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.NextExecutionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringTransactions = `-- name: ListRecurringTransactions :many
SELECT id, user_id, title, type, amount, category_id, sub_category_id, wallet_id, frequency, start_date, end_date, is_active, next_execution_date, created_at, updated_at
FROM recurring_transactions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRecurringTransactions(ctx context.Context, userID int32) ([]RecurringTransaction, error) {
	rows, err := q.db.Query(ctx, listRecurringTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringTransaction
	for rows.Next() {
		var i RecurringTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Type,
			&i.Amount,
			&i.CategoryID,
			&i.SubCategoryID,
			&i.WalletID,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.NextExecutionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNextExecutionDate = `-- name: UpdateNextExecutionDate :one
UPDATE recurring_transactions
SET next_execution_date = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, title, type, amount, category_id, sub_category_id, wallet_id, frequency, start_date, end_date, is_active, next_execution_date, created_at, updated_at
`

type UpdateNextExecutionDateParams struct {
	ID                int32       `json:"id"`
	NextExecutionDate pgtype.Date `json:"next_execution_date"`
}

func (q *Queries) UpdateNextExecutionDate(ctx context.Context, arg UpdateNextExecutionDateParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, updateNextExecutionDate, arg.ID, arg.NextExecutionDate)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.Amount,
		&i.CategoryID,
		&i.SubCategoryID,
		&i.WalletID,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.NextExecutionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRecurringTransaction = `-- name: UpdateRecurringTransaction :one
UPDATE recurring_transactions
SET title = $3, type = $4, amount = $5, category_id = $6, sub_category_id = $7,
    wallet_id = $8, frequency = $9, start_date = $10, end_date = $11,
    next_execution_date = $12, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, type, amount, category_id, sub_category_id, wallet_id, frequency, start_date, end_date, is_active, next_execution_date, created_at, updated_at
`

type UpdateRecurringTransactionParams struct {
	ID                int32          `json:"id"`
	UserID            int32          `json:"user_id"`
	Title             string         `json:"title"`
	Type              string         `json:"type"`
	Amount            pgtype.Numeric `json:"amount"`
	CategoryID        pgtype.Int4    `json:"category_id"`
	SubCategoryID     pgtype.Int4    `json:"sub_category_id"`
	WalletID          pgtype.Int4    `json:"wallet_id"`
	Frequency         string         `json:"frequency"`
	StartDate         pgtype.Date    `json:"start_date"`
	EndDate           pgtype.Date    `json:"end_date"`
	NextExecutionDate pgtype.Date    `json:"next_execution_date"`
}

func (q *Queries) UpdateRecurringTransaction(ctx context.Context, arg UpdateRecurringTransactionParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, updateRecurringTransaction,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Type,
		arg.Amount,
		arg.CategoryID,
		arg.SubCategoryID,
		arg.WalletID,
		arg.Frequency,
		arg.StartDate,
		arg.EndDate,
		arg.NextExecutionDate,
	)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.Amount,
		&i.CategoryID,
		&i.SubCategoryID,
		&i.WalletID,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.NextExecutionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
