// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTransactionsByDateRange = `-- name: GetTransactionsByDateRange :many
SELECT t.id, t.user_id, t.type, t.amount, t.description,
       t.category_id, t.sub_category_id,
       t.wallet_id, w.name as wallet_name,
       t.receipt_image_url,
       t.transaction_date, t.created_at, t.updated_at
FROM transactions t
LEFT JOIN wallets w ON t.wallet_id = w.id
WHERE t.user_id = $1
  AND t.transaction_date >= $2
  AND t.transaction_date <= $3
ORDER BY t.transaction_date DESC, t.created_at DESC
`

type GetTransactionsByDateRangeParams struct {
	UserID            int32       `json:"user_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type GetTransactionsByDateRangeRow struct {
	ID              int32            `json:"id"`
	UserID          int32            `json:"user_id"`
	Type            string           `json:"type"`
	Amount          pgtype.Numeric   `json:"amount"`
	Description     pgtype.Text      `json:"description"`
	CategoryID      pgtype.Int4      `json:"category_id"`
	SubCategoryID   pgtype.Int4      `json:"sub_category_id"`
	WalletID        pgtype.Int4      `json:"wallet_id"`
	WalletName      pgtype.Text      `json:"wallet_name"`
	ReceiptImageUrl pgtype.Text      `json:"receipt_image_url"`
	TransactionDate pgtype.Date      `json:"transaction_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetTransactionsByDateRange(ctx context.Context, arg GetTransactionsByDateRangeParams) ([]GetTransactionsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsByDateRange, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByDateRangeRow
	for rows.Next() {
		var i GetTransactionsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.CategoryID,
			&i.SubCategoryID,
			&i.WalletID,
			&i.WalletName,
			&i.ReceiptImageUrl,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
