// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, type, amount, description, category_id, transaction_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, amount, description, category_id, transaction_date, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID          int32          `json:"user_id"`
	Type            string         `json:"type"`
	Amount          pgtype.Numeric `json:"amount"`
	Description     pgtype.Text    `json:"description"`
	CategoryID      pgtype.Int4    `json:"category_id"`
	TransactionDate pgtype.Date    `json:"transaction_date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.CategoryID,
		arg.TransactionDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.CategoryID,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT 
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END), 0)::numeric AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0)::numeric AS total_expense
FROM transactions
WHERE user_id = $1
`

type GetDashboardStatsRow struct {
	TotalIncome  pgtype.Numeric `json:"total_income"`
	TotalExpense pgtype.Numeric `json:"total_expense"`
}

func (q *Queries) GetDashboardStats(ctx context.Context, userID int32) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats, userID)
	var i GetDashboardStatsRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT t.id, t.user_id, t.type, t.amount, t.description, t.category_id, c.name as category_name, t.transaction_date, t.created_at, t.updated_at
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
WHERE t.id = $1 AND t.user_id = $2 LIMIT 1
`

type GetTransactionParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetTransactionRow struct {
	ID              int32            `json:"id"`
	UserID          int32            `json:"user_id"`
	Type            string           `json:"type"`
	Amount          pgtype.Numeric   `json:"amount"`
	Description     pgtype.Text      `json:"description"`
	CategoryID      pgtype.Int4      `json:"category_id"`
	CategoryName    pgtype.Text      `json:"category_name"`
	TransactionDate pgtype.Date      `json:"transaction_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.CategoryID,
		&i.CategoryName,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT t.id, t.user_id, t.type, t.amount, t.description, t.category_id, c.name as category_name, t.transaction_date, t.created_at, t.updated_at
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
WHERE t.user_id = $1
ORDER BY t.transaction_date DESC, t.created_at DESC
`

type ListTransactionsRow struct {
	ID              int32            `json:"id"`
	UserID          int32            `json:"user_id"`
	Type            string           `json:"type"`
	Amount          pgtype.Numeric   `json:"amount"`
	Description     pgtype.Text      `json:"description"`
	CategoryID      pgtype.Int4      `json:"category_id"`
	CategoryName    pgtype.Text      `json:"category_name"`
	TransactionDate pgtype.Date      `json:"transaction_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListTransactions(ctx context.Context, userID int32) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.CategoryID,
			&i.CategoryName,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET type = $3, amount = $4, description = $5, category_id = $6, transaction_date = $7, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, amount, description, category_id, transaction_date, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID              int32          `json:"id"`
	UserID          int32          `json:"user_id"`
	Type            string         `json:"type"`
	Amount          pgtype.Numeric `json:"amount"`
	Description     pgtype.Text    `json:"description"`
	CategoryID      pgtype.Int4    `json:"category_id"`
	TransactionDate pgtype.Date    `json:"transaction_date"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.CategoryID,
		arg.TransactionDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.CategoryID,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
