// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, type, amount, description, category_id, sub_category_id, wallet_id, transaction_date, receipt_image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, type, amount, description, category_id, sub_category_id, wallet_id, receipt_image_url, transaction_date, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID          int32          `json:"user_id"`
	Type            string         `json:"type"`
	Amount          pgtype.Numeric `json:"amount"`
	Description     pgtype.Text    `json:"description"`
	CategoryID      pgtype.Int4    `json:"category_id"`
	SubCategoryID   pgtype.Int4    `json:"sub_category_id"`
	WalletID        pgtype.Int4    `json:"wallet_id"`
	TransactionDate pgtype.Date    `json:"transaction_date"`
	ReceiptImageUrl pgtype.Text    `json:"receipt_image_url"`
}

type CreateTransactionRow struct {
	ID              int32            `json:"id"`
	UserID          int32            `json:"user_id"`
	Type            string           `json:"type"`
	Amount          pgtype.Numeric   `json:"amount"`
	Description     pgtype.Text      `json:"description"`
	CategoryID      pgtype.Int4      `json:"category_id"`
	SubCategoryID   pgtype.Int4      `json:"sub_category_id"`
	WalletID        pgtype.Int4      `json:"wallet_id"`
	ReceiptImageUrl pgtype.Text      `json:"receipt_image_url"`
	TransactionDate pgtype.Date      `json:"transaction_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.CategoryID,
		arg.SubCategoryID,
		arg.WalletID,
		arg.TransactionDate,
		arg.ReceiptImageUrl,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.CategoryID,
		&i.SubCategoryID,
		&i.WalletID,
		&i.ReceiptImageUrl,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END), 0)::numeric AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0)::numeric AS total_expense
FROM transactions
WHERE user_id = $1
`

type GetDashboardStatsRow struct {
	TotalIncome  pgtype.Numeric `json:"total_income"`
	TotalExpense pgtype.Numeric `json:"total_expense"`
}

func (q *Queries) GetDashboardStats(ctx context.Context, userID int32) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats, userID)
	var i GetDashboardStatsRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT t.id, t.user_id, t.type, t.amount, t.description,
       t.category_id, t.sub_category_id,
       t.wallet_id, w.name as wallet_name,
       t.receipt_image_url,
       t.transaction_date, t.created_at, t.updated_at
FROM transactions t
LEFT JOIN wallets w ON t.wallet_id = w.id
WHERE t.id = $1 AND t.user_id = $2 LIMIT 1
`

type GetTransactionParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetTransactionRow struct {
	ID              int32            `json:"id"`
	UserID          int32            `json:"user_id"`
	Type            string           `json:"type"`
	Amount          pgtype.Numeric   `json:"amount"`
	Description     pgtype.Text      `json:"description"`
	CategoryID      pgtype.Int4      `json:"category_id"`
	SubCategoryID   pgtype.Int4      `json:"sub_category_id"`
	WalletID        pgtype.Int4      `json:"wallet_id"`
	WalletName      pgtype.Text      `json:"wallet_name"`
	ReceiptImageUrl pgtype.Text      `json:"receipt_image_url"`
	TransactionDate pgtype.Date      `json:"transaction_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.CategoryID,
		&i.SubCategoryID,
		&i.WalletID,
		&i.WalletName,
		&i.ReceiptImageUrl,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT t.id, t.user_id, t.type, t.amount, t.description,
       t.category_id, t.sub_category_id,
       t.wallet_id, w.name as wallet_name,
       t.receipt_image_url,
       t.transaction_date, t.created_at, t.updated_at
FROM transactions t
LEFT JOIN wallets w ON t.wallet_id = w.id
WHERE t.user_id = $1
ORDER BY t.transaction_date DESC, t.created_at DESC
`

type ListTransactionsRow struct {
	ID              int32            `json:"id"`
	UserID          int32            `json:"user_id"`
	Type            string           `json:"type"`
	Amount          pgtype.Numeric   `json:"amount"`
	Description     pgtype.Text      `json:"description"`
	CategoryID      pgtype.Int4      `json:"category_id"`
	SubCategoryID   pgtype.Int4      `json:"sub_category_id"`
	WalletID        pgtype.Int4      `json:"wallet_id"`
	WalletName      pgtype.Text      `json:"wallet_name"`
	ReceiptImageUrl pgtype.Text      `json:"receipt_image_url"`
	TransactionDate pgtype.Date      `json:"transaction_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListTransactions(ctx context.Context, userID int32) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.CategoryID,
			&i.SubCategoryID,
			&i.WalletID,
			&i.WalletName,
			&i.ReceiptImageUrl,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET type = $3, amount = $4, description = $5, category_id = $6, sub_category_id = $7,
    wallet_id = $8, transaction_date = $9, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, amount, description, category_id, sub_category_id, wallet_id, receipt_image_url, transaction_date, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID              int32          `json:"id"`
	UserID          int32          `json:"user_id"`
	Type            string         `json:"type"`
	Amount          pgtype.Numeric `json:"amount"`
	Description     pgtype.Text    `json:"description"`
	CategoryID      pgtype.Int4    `json:"category_id"`
	SubCategoryID   pgtype.Int4    `json:"sub_category_id"`
	WalletID        pgtype.Int4    `json:"wallet_id"`
	TransactionDate pgtype.Date    `json:"transaction_date"`
}

type UpdateTransactionRow struct {
	ID              int32            `json:"id"`
	UserID          int32            `json:"user_id"`
	Type            string           `json:"type"`
	Amount          pgtype.Numeric   `json:"amount"`
	Description     pgtype.Text      `json:"description"`
	CategoryID      pgtype.Int4      `json:"category_id"`
	SubCategoryID   pgtype.Int4      `json:"sub_category_id"`
	WalletID        pgtype.Int4      `json:"wallet_id"`
	ReceiptImageUrl pgtype.Text      `json:"receipt_image_url"`
	TransactionDate pgtype.Date      `json:"transaction_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (UpdateTransactionRow, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.CategoryID,
		arg.SubCategoryID,
		arg.WalletID,
		arg.TransactionDate,
	)
	var i UpdateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.CategoryID,
		&i.SubCategoryID,
		&i.WalletID,
		&i.ReceiptImageUrl,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
