// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustWalletBalance = `-- name: AdjustWalletBalance :one
UPDATE wallets
SET balance = balance + $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, name, type, created_at, updated_at, currency, balance, goals
`

type AdjustWalletBalanceParams struct {
	Balance pgtype.Numeric `json:"balance"`
	ID      int32          `json:"id"`
	UserID  int32          `json:"user_id"`
}

func (q *Queries) AdjustWalletBalance(ctx context.Context, arg AdjustWalletBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, adjustWalletBalance, arg.Balance, arg.ID, arg.UserID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Currency,
		&i.Balance,
		&i.Goals,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (user_id, name, type, currency, balance, goals, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, user_id, name, type, created_at, updated_at, currency, balance, goals
`

type CreateWalletParams struct {
	UserID   int32          `json:"user_id"`
	Name     string         `json:"name"`
	Type     string         `json:"type"`
	Currency string         `json:"currency"`
	Balance  pgtype.Numeric `json:"balance"`
	Goals    pgtype.Text    `json:"goals"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Balance,
		arg.Goals,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Currency,
		&i.Balance,
		&i.Goals,
	)
	return i, err
}

const deleteWallet = `-- name: DeleteWallet :exec
DELETE FROM wallets WHERE id = $1 AND user_id = $2
`

type DeleteWalletParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteWallet(ctx context.Context, arg DeleteWalletParams) error {
	_, err := q.db.Exec(ctx, deleteWallet, arg.ID, arg.UserID)
	return err
}

const getWallet = `-- name: GetWallet :one
SELECT id, user_id, name, type, created_at, updated_at, currency, balance, goals FROM wallets
WHERE id = $1 AND user_id = $2
`

type GetWalletParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetWallet(ctx context.Context, arg GetWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, arg.ID, arg.UserID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Currency,
		&i.Balance,
		&i.Goals,
	)
	return i, err
}

const listWallets = `-- name: ListWallets :many
SELECT id, user_id, name, type, created_at, updated_at, currency, balance, goals FROM wallets
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListWallets(ctx context.Context, userID int32) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, listWallets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wallet
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Currency,
			&i.Balance,
			&i.Goals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWallet = `-- name: UpdateWallet :one
UPDATE wallets
SET name = $1, type = $2, currency = $3, balance = $4, goals = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, name, type, created_at, updated_at, currency, balance, goals
`

type UpdateWalletParams struct {
	Name     string         `json:"name"`
	Type     string         `json:"type"`
	Currency string         `json:"currency"`
	Balance  pgtype.Numeric `json:"balance"`
	Goals    pgtype.Text    `json:"goals"`
	ID       int32          `json:"id"`
	UserID   int32          `json:"user_id"`
}

func (q *Queries) UpdateWallet(ctx context.Context, arg UpdateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWallet,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Balance,
		arg.Goals,
		arg.ID,
		arg.UserID,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Currency,
		&i.Balance,
		&i.Goals,
	)
	return i, err
}
