// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type CreateWalletParams struct {
	UserID int32  `json:"user_id"`
	Name   string `json:"name"`
	Type   string `json:"type"`
}

type UpdateWalletParams struct {
	Name   string `json:"name"`
	Type   string `json:"type"`
	ID     int32  `json:"id"`
	UserID int32  `json:"user_id"`
}

type DeleteWalletParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetWalletParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (user_id, name, type, created_at, updated_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, user_id, name, type, created_at, updated_at`

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.UserID, arg.Name, arg.Type)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT id, user_id, name, type, created_at, updated_at FROM wallets
WHERE id = $1 AND user_id = $2`

func (q *Queries) GetWallet(ctx context.Context, arg GetWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, arg.ID, arg.UserID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWallets = `-- name: ListWallets :many
SELECT id, user_id, name, type, created_at, updated_at FROM wallets
WHERE user_id = $1
ORDER BY name`

func (q *Queries) ListWallets(ctx context.Context, userID int32) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, listWallets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wallet
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateWallet = `-- name: UpdateWallet :one
UPDATE wallets
SET name = $1, type = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3 AND user_id = $4
RETURNING id, user_id, name, type, created_at, updated_at`

func (q *Queries) UpdateWallet(ctx context.Context, arg UpdateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWallet, arg.Name, arg.Type, arg.ID, arg.UserID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWallet = `-- name: DeleteWallet :exec
DELETE FROM wallets WHERE id = $1 AND user_id = $2`

func (q *Queries) DeleteWallet(ctx context.Context, arg DeleteWalletParams) error {
	_, err := q.db.Exec(ctx, deleteWallet, arg.ID, arg.UserID)
	return err
}
